version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: auromart-backend-prod
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://auroconnect:auroconnect123@3.249.132.231:3306/auroconnect_b2b
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - CORS_ORIGINS=http://localhost:3001,https://yourdomain.com
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - auromart-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: auromart-frontend-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - NODE_ENV=production
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - auromart-network

networks:
  auromart-network:
    driver: bridge
